name: CI

on:
  push:
    branches:
      - main
      - CI/CD
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Maven (run tests)
        run: mvn -f src/quan_ly_chi_tieu_ca_nhan/pom.xml clean install
